Repository intel-analytics/analytics-zoo, pull requests merged in 2018-10, with the labels that each got.

#684 Add TextSet and update TextClassification examples
  pyzoo/test/zoo/feature/text/test_text_set.py
  pyzoo/test/zoo/resources/news20/alt.atheism/51158
  pyzoo/test/zoo/resources/news20/alt.atheism/51186
  pyzoo/test/zoo/resources/news20/rec.autos/101556
  pyzoo/zoo/examples/run-example-tests.sh
  pyzoo/zoo/examples/textclassification/README.md
  pyzoo/zoo/examples/textclassification/text_classification.py
  pyzoo/zoo/feature/common.py
  pyzoo/zoo/feature/text/__init__.py
  pyzoo/zoo/feature/text/text_feature.py
  pyzoo/zoo/feature/text/text_set.py
  pyzoo/zoo/feature/text/transformer.py
  pyzoo/zoo/models/textclassification/text_classifier.py
  pyzoo/zoo/pipeline/api/keras/engine/topology.py
  zoo/src/main/scala/com/intel/analytics/zoo/examples/textclassification/README.md
  zoo/src/main/scala/com/intel/analytics/zoo/examples/textclassification/TextClassification.scala
  zoo/src/main/scala/com/intel/analytics/zoo/feature/common/Preprocessing.scala
  zoo/src/main/scala/com/intel/analytics/zoo/feature/image/ImageSet.scala
  zoo/src/main/scala/com/intel/analytics/zoo/feature/python/PythonTextFeature.scala
  zoo/src/main/scala/com/intel/analytics/zoo/feature/text/TextFeature.scala
  zoo/src/main/scala/com/intel/analytics/zoo/feature/text/TextSet.scala
  zoo/src/main/scala/com/intel/analytics/zoo/feature/text/WordIndexer.scala
  zoo/src/main/scala/com/intel/analytics/zoo/models/textclassification/TextClassifier.scala
  zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/Embedding.scala
  zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala
  zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala
  zoo/src/test/integration-test.robot
  zoo/src/test/resources/news20/alt.atheism/51158
  zoo/src/test/resources/news20/alt.atheism/51186
  zoo/src/test/resources/news20/rec.autos/101556
  zoo/src/test/resources/news20/sci.space/60209
  zoo/src/test/resources/news20/sci.space/60249
  zoo/src/test/scala/com/intel/analytics/zoo/feature/text/TextFeatureSpec.scala
  zoo/src/test/scala/com/intel/analytics/zoo/feature/text/TextFeatureToSampleSpec.scala
  zoo/src/test/scala/com/intel/analytics/zoo/feature/text/TextSetSpec.scala
  zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/EmbeddingSpec.scala
  zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/models/TopologySpec.scala
Labels: text

#664 Update pip dependency for release 0.3
  docs/docs/PythonUserGuide/install.md
  docs/docs/ScalaUserGuide/install.md
  pyzoo/setup.py
Labels: release

#739 Add TextPredictor
  zoo/src/main/scala/com/intel/analytics/zoo/feature/text/TextFeature.scala
  zoo/src/main/scala/com/intel/analytics/zoo/feature/text/TextPredictor.scala
  zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/models/Topology.scala
  zoo/src/test/scala/com/intel/analytics/zoo/feature/text/TextSetSpec.scala
Labels: text

#803 Update website doc for TextClassifier
  docs/docs/APIGuide/Models/text-classification.md
  docs/docs/ProgrammingGuide/text-classification.md
  pyzoo/zoo/models/textclassification/text_classifier.py
  zoo/src/main/scala/com/intel/analytics/zoo/models/textclassification/TextClassifier.scala
Labels: document

#785 fix document in apps/object detection and scala install
  apps/object-detection/README.md
  docs/docs/ScalaUserGuide/install.md
Labels: document

#786 update readme for python nnframes examples
  pyzoo/zoo/examples/nnframes/finetune/README.md
  pyzoo/zoo/examples/nnframes/finetune/image_finetuning_example.py
  pyzoo/zoo/examples/nnframes/imageInference/ImageInferenceExample.py
  pyzoo/zoo/examples/nnframes/imageInference/README.md
  pyzoo/zoo/examples/nnframes/imageTransferLearning/ImageTransferLearningExample.py
  pyzoo/zoo/examples/nnframes/imageTransferLearning/README.md
Labels: document

#802 Update readme for apps/dogs-vs-cats
  apps/dogs-vs-cats/README.md
Labels: document

#778 readme update for NNFrames Scala examples
  zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/finetune/ImageFinetune.scala
  zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/finetune/README.md
  zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/finetune/sample_training_data.py
  zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/imageInference/ImageInferenceExample.scala
  zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/imageInference/README.md
  zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/imageTransferLearning/ImageTransferLearning.scala
  zoo/src/main/scala/com/intel/analytics/zoo/examples/nnframes/imageTransferLearning/README.md
Labels: document

#783 Add script for pip example integration test
  pyzoo/zoo/examples/run-example-tests-pip.sh
Labels: release, test

#804 Add script for pip app integration test
  apps/run-app-tests-pip.sh
  apps/run-app-tests.sh
Labels: release, test

#807 update readme for image similarity notebook
  apps/image-similarity/README.md
Labels: document

#853 Change back bigdl version to 0.6.0
  docs/docs/PythonUserGuide/install.md
  docs/docs/ScalaUserGuide/install.md
  pyzoo/setup.py
  zoo/pom.xml
Labels: release

#814 Update README for analytics-zoo/pyzoo/zoo/examples/autograd
  pyzoo/zoo/examples/autograd/README.md
Labels: document

#810 Add KNRM model
  pyzoo/test/zoo/models/textmatching/__init__.py
  pyzoo/test/zoo/models/textmatching/test_knrm.py
  pyzoo/zoo/models/textmatching/__init__.py
  pyzoo/zoo/models/textmatching/knrm.py
  pyzoo/zoo/models/textmatching/text_matcher.py
  pyzoo/zoo/pipeline/api/keras/layers/embeddings.py
  zoo/src/main/scala/com/intel/analytics/zoo/models/python/PythonZooModel.scala
  zoo/src/main/scala/com/intel/analytics/zoo/models/textmatching/KNRM.scala
  zoo/src/main/scala/com/intel/analytics/zoo/models/textmatching/TextMatcher.scala
  zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/Embedding.scala
  zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/WordEmbedding.scala
  zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala
  zoo/src/test/scala/com/intel/analytics/zoo/models/textmatching/KNRMSpec.scala
  zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/EmbeddingSpec.scala
Labels: text

#864 Update readme for scala and python examples/imageclassification
  pyzoo/zoo/examples/imageclassification/README.md
  zoo/src/main/scala/com/intel/analytics/zoo/examples/imageclassification/README.md
Labels: document

#791 Update readme for apps/recommendation
  apps/recommendation-ncf/README.md
  apps/recommendation-wide-n-deep/README.md
Labels: document

#780 Readme update about sentiment-analysis app and imageclassification python example
  apps/sentiment-analysis/README.md
  pyzoo/zoo/examples/imageclassification/README.md
Labels: document

#817 Update readme for apps/image-augmentation-3d
  apps/image-augmentation-3d/README.md
Labels: document

#844 update readme for apps/fraud-detection
  apps/fraud-detection/README.md
Labels: document

#842 Update README.md for variational-autoencoder
  apps/variational-autoencoder/README.md
Labels: document

#845 fix two issues with virtual environment
  docs/docs/PythonUserGuide/run.md
  scripts/python_package.sh
Labels: high priority

#908 Bump version to 0.3
  docker/Dockerfile
  docs/docs/PythonUserGuide/install.md
  docs/docs/ScalaUserGuide/install.md
  pom.xml
  pyzoo/zoo/version.py
  zoo/pom.xml
Labels: release
