Repository intel-analytics/analytics-zoo, pull requests merged in 2019-01, with the labels that each got.

#1014 add keras docs by manfei
  docs/docs/KerasStyleAPIGuide/Layers/activation.md
  docs/docs/KerasStyleAPIGuide/Layers/convolutional.md
  docs/docs/KerasStyleAPIGuide/Layers/core.md
  docs/docs/KerasStyleAPIGuide/Layers/dropout.md
Labels: document

#925 Seq2seq onmt
  pyzoo/dev/diff.py
  zoo/src/main/scala/com/intel/analytics/zoo/common/Utils.scala
  zoo/src/main/scala/com/intel/analytics/zoo/models/seq2seq/Bridge.scala
  zoo/src/main/scala/com/intel/analytics/zoo/models/seq2seq/Encoder.scala
  zoo/src/main/scala/com/intel/analytics/zoo/models/seq2seq/RNNDecoder.scala
  zoo/src/main/scala/com/intel/analytics/zoo/models/seq2seq/RNNEncoder.scala
  zoo/src/main/scala/com/intel/analytics/zoo/models/seq2seq/Seq2seq.scala
  zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/InternalRecurrent.scala
  zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/InternalSplitTensor.scala
  zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/KerasLayerWrapper.scala
  zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/Recurrent.scala
  zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/SelectTable.scala
  zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/SplitTensor.scala
  zoo/src/test/scala/com/intel/analytics/zoo/models/seq2seq/Seq2seqSpec.scala
  zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/SplitTensorSpec.scala
  zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/SelectTableSpec.scala
  zoo/src/test/scala/com/intel/analytics/zoo/pipeline/api/keras/layers/internal/InternalSplitTensorSpec.scala
Labels: text

#1029 Add Keras Docs Two By Manfei
  docs/docs/KerasStyleAPIGuide/Layers/activation.md
  docs/docs/KerasStyleAPIGuide/Layers/convolutional.md
  docs/docs/KerasStyleAPIGuide/Layers/core.md
  docs/docs/KerasStyleAPIGuide/Layers/dropout.md
  docs/docs/KerasStyleAPIGuide/Layers/embedding.md
  docs/docs/KerasStyleAPIGuide/Layers/pooling.md
  zoo/src/main/scala/com/intel/analytics/zoo/pipeline/api/keras/python/PythonZooKeras.scala
Labels: document

#1053 add Seq2seq doc and more python seq2seq apis
  docs/docs/APIGuide/Models/seq2seq.md
  docs/docs/ProgrammingGuide/seq2seq.md
  pyzoo/test/zoo/models/seq2seq/test_seq2seq.py
  pyzoo/zoo/models/seq2seq/seq2seq.py
  zoo/src/main/scala/com/intel/analytics/zoo/models/python/PythonZooModel.scala
  zoo/src/main/scala/com/intel/analytics/zoo/models/seq2seq/Seq2seq.scala
  zoo/src/test/scala/com/intel/analytics/zoo/models/seq2seq/Seq2seqSpec.scala
Labels: document, enhancement, python

#1051 Add KNRM, QARanker website doc
  README.md
  docs/docs/APIGuide/FeatureEngineering/relation.md
  docs/docs/APIGuide/FeatureEngineering/text.md
  docs/docs/APIGuide/Models/text-classification.md
  docs/docs/APIGuide/Models/text-matching.md
  docs/docs/ProgrammingGuide/text-classification.md
  docs/docs/ProgrammingGuide/text-matching.md
  docs/docs/ProgrammingGuide/usercases-overview.md
  docs/docs/ProgrammingGuide/workingwithtexts.md
  docs/docs/PythonUserGuide/examples.md
  docs/docs/ScalaUserGuide/examples.md
  docs/docs/index.md
  docs/mkdocs.yml
  pyzoo/zoo/examples/textclassification/README.md
  pyzoo/zoo/examples/textclassification/text_classification.py
  pyzoo/zoo/feature/text/text_set.py
  zoo/src/main/scala/com/intel/analytics/zoo/feature/common/Relations.scala
  zoo/src/main/scala/com/intel/analytics/zoo/feature/python/PythonTextFeature.scala
  zoo/src/main/scala/com/intel/analytics/zoo/feature/text/TextSet.scala
Labels: document

#1103 Add QARanker Python example to integration
  pyzoo/zoo/examples/run-example-tests-pip.sh
  pyzoo/zoo/examples/run-example-tests.sh
Labels: test

#1008 [Doc] Optimization Doc
  docs/docs/KerasStyleAPIGuide/Optimization/loss.md
  docs/docs/KerasStyleAPIGuide/Optimization/objectives.md
  docs/docs/KerasStyleAPIGuide/Optimization/optimizer.md
  docs/docs/KerasStyleAPIGuide/Optimization/training.md
Labels: document

#1108 fix wnd integration test
  zoo/src/test/integration-test.robot
Labels: test
