Repository intel-analytics/analytics-zoo, pull requests merged in 2020-03, with the labels that each got.

#2085 add lstm network traffic use case
  pyzoo/zoo/zouwu/use-case/extract_data.sh
  pyzoo/zoo/zouwu/use-case/get_data.sh
  pyzoo/zoo/zouwu/use-case/time_series_forecasting_network_traffic.ipynb
Labels: automl

#2088 refactor mtnet for exposing model
  pyzoo/zoo/automl/model/MTNet_keras.py
Labels: automl

#2092 add mtnet multivariate forecasting and change dir
  pyzoo/zoo/zouwu/use-case/network_traffic/extract_data.sh
  pyzoo/zoo/zouwu/use-case/network_traffic/get_data.sh
  pyzoo/zoo/zouwu/use-case/network_traffic/time_series_forecasting_network_traffic.ipynb
  pyzoo/zoo/zouwu/use-case/time_series_forecasting_network_traffic.ipynb
Labels: automl

#2036 Polish doc style of Google colab
  docs/docs/ProgrammingGuide/run-notebook-colab.md
  docs/mkdocs.yml
Labels: document

#2113 add autots use case
  pyzoo/zoo/zouwu/use-case/network_traffic/README.md
  pyzoo/zoo/zouwu/use-case/network_traffic/network_traffic_autots_forecasting.ipynb
  pyzoo/zoo/zouwu/use-case/network_traffic/network_traffic_forecasting.ipynb
  pyzoo/zoo/zouwu/use-case/network_traffic/network_traffic_model_forecasting.ipynb
Labels: zouwu
